# -*- coding: utf-8 -*-
"""Creacion de API - Proyecto en Analitica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1NNtO18J4sFQlk98bMgtSJ-Fywap9MX

# Guardar el modelo
"""

"""# Generar API"""

import joblib

# Cargar el modelo
model = joblib.load('best_model_SqEr.pkl')

# Ejemplo de datos para la predicción
example_data = [12,  136, 4, 2022, 13575692, 2]

# Realizar la predicción
prediction = model.predict([example_data])

# Imprimir el resultado
print(prediction)

from flask import Flask, request, jsonify
import pickle

app = Flask(__name__)
# Cargar el modelo
model = joblib.load('best_model_SqEr.pkl')

# Ruta para la API
@app.route('/api/prediction', methods=['POST'])
def predict():
    # Obtener los datos de la petición HTTP
    data = request.get_json()

    # Extraer los valores de las variables
    departamento = data['Departamento']
    cai_departamentos = data['CAI_Departamentos']
    mes = data['Mes']
    ano = data['Ano']
    poblacion = data['Poblacion']
    pobreza_monetaria = data['Pobreza_Monetaria']

    # Realizar la predicción utilizando el modelo cargado
    prediction = model.predict([[departamento, cai_departamentos, mes, ano, poblacion, pobreza_monetaria]])

    # Devolver la predicción como respuesta
    response = {'prediction': prediction[0]}
    return jsonify(response)

if __name__ == '__main__':
    app.run()